import json      
import os    
import sys     
import uuid  

file_name = "students.json"


def load_data()->dict:
    if not os.path.exists(file_name):
        return {}
    
    try:
        with open(file_name, 'r') as f:
            return json.load(f) 
    except OSError as e:
        print(f'error reading file: {e}')
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f'invalid JSON syntax: {e}')
        sys.exit(1)


def save_data(data: dict):
    try:
        with open(file_name, 'w') as f: 
            json.dump(data, f, indent= 4)
    except OSError as e:
        print(f'error opening file: {e}')


def add_student(name: str):
    student_id_len = 16
    n_hyphens = 3                  #number of hyphens between the first 16 chars in the id generated by uuid4

    data = load_data()
    while True:
        student_id = str(uuid.uuid4()).replace('-', '')[:student_id_len + n_hyphens]
        if student_id not in data:
            break
    data[student_id] = {
            "id": student_id,
            "name": name,
            "courses": []
    }
    save_data(data)
    print(f"✅ Added successfully: {name} (ID: {student_id})")

